### ISSUE TITLE
Failed to run `cargo install perseus-cli` without the `--locked` flag

### ISSUE THREAD

**Issue by saona-raimundo** [framesurge/perseus#269] opened 2023-04-08 18:54 UTC
This issue is reporting a bug in the website.
- The issue occurred on <https://framesurge.sh/perseus/en-US/docs/0.3.4/tutorials/hello-world>.
- Issue categories: Typos and grammar errors
- Other category: Functionality
The user described the issue as follows:
> When I run `cargo install perseus-cli`, I get the following error.
```
cargo install perseus-cli
    Updating crates.io index
  Installing perseus-cli v0.3.6
error: failed to compile `perseus-cli v0.3.6`, intermediate artifacts can be found at `C:\Users\rasau\AppData\Local\Temp\cargo-installesoazn`

Caused by:
  failed to select a version for the requirement `cargo_toml = "^0.9"`
  candidate versions found which didn't match: 0.15.2, 0.15.1, 0.15.0, ...
  location searched: crates.io index
  required by package `perseus-cli v0.3.6`
```

For me, the fix was to run `cargo install perseus-cli --locked`.
I wanted to propose to add the `--locked` flag to the tutorial. 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLXdlYnNpdGU=

</details>

**Comment by saona-raimundo** [comment] 2023-04-08 19:17
Note: This has nothing to do with requiring `perl` to build openssl-sys on Windows.

**Comment by arctic-hen7** [comment] 2023-04-09 00:10
Yeah, this relates to a previous upstream issue in `cargo_toml` that makes downloading v0.3 of the Perseus CLI difficult. I would recommend moving to v0.4, which will be released in stable today, but a PR to add this flag to the old docs is welcome!

**Comment by saona-raimundo** [comment] 2023-04-13 07:18
I confirm that moving to v0.4 works :) Thanks!

I wonder, if it happened before, why should it not happen again in v0.4 with some other upstream crate?
Is there a disadvantage to adding the `--locked` flag? (other than being a longer script)

**Comment by arctic-hen7** [comment] 2023-04-13 22:46
The bug was caused by one particular crate that had almost every existing version yanked, which is extremely irregular, whereas Perseus itself generally allows its dependencies to update their minor versions, so I don't think adding `--locked` outside of v0.3 is worth it. I strongly doubt anything like this would happen again!

**Closed** 2023-04-14 06:50 UTC
Labels: C-bug, A-website, tribble-reported
