### ISSUE TITLE
Tokio build fails in v0.3.x

### ISSUE THREAD

**Issue by coruscateor** [framesurge/perseus#190] opened 2022-09-15 05:39 UTC
I'm trying to build the Perseus hello-world example following:

https://framesurge.sh/perseus/en-US/docs/0.3.4/tutorials/hello-world

I get:

```
PS F:\SoftwareProjects\Rust\my-perseus-app> perseus serve
⠈ [1/4]  Generating your app...
  [2/4]  Building your app to Wasm...failed!
⠂ [3/4]  Building server...
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.4
   Compiling quote v1.0.21
   Compiling syn v1.0.99
   Compiling autocfg v1.1.0
   Compiling serde_derive v1.0.144
   Compiling serde v1.0.144
   Compiling cfg-if v1.0.0
   Compiling wasm-bindgen-shared v0.2.83
   Compiling log v0.4.17
   Compiling once_cell v1.14.0
   Compiling serde_json v1.0.85
   Compiling bumpalo v3.11.0
   Compiling wasm-bindgen v0.2.83
   Compiling itoa v1.0.3
   Compiling ryu v1.0.11
   Compiling memchr v2.5.0
   Compiling version_check v0.9.4
   Compiling static_assertions v1.1.0
   Compiling futures-core v0.3.24
   Compiling futures-task v0.3.24
   Compiling pin-project-lite v0.2.9
   Compiling futures-channel v0.3.24
   Compiling futures-util v0.3.24
   Compiling fnv v1.0.7
   Compiling strsim v0.10.0
   Compiling hashbrown v0.12.3
   Compiling ident_case v1.0.1
   Compiling futures-sink v0.3.24
   Compiling libc v0.2.132
   Compiling futures-io v0.3.24
   Compiling minimal-lexical v0.2.1
   Compiling thiserror v1.0.35
   Compiling smallvec v1.9.0
   Compiling utf8-width v0.1.6
   Compiling pin-utils v0.1.0
   Compiling bytes v1.2.1
   Compiling async-trait v0.1.57
   Compiling paste v1.0.9
   Compiling unicode-xid v0.2.3
   Compiling fmterr v0.1.1
   Compiling urlencoding v2.1.2
   Compiling getrandom v0.2.7
   Compiling lexical-util v0.8.5
   Compiling indexmap v1.9.1
   Compiling slab v0.4.7
   Compiling num-traits v0.2.15
   Compiling tokio v1.21.1
   Compiling num-integer v0.1.45
   Compiling html-escape v0.2.11
   Compiling ahash v0.7.6
   Compiling http v0.2.8
   Compiling lexical-write-integer v0.8.5
   Compiling lexical-parse-integer v0.8.6
   Compiling time v0.1.44
   Compiling nom v7.1.1
error: Only features sync,macros,io-util,rt,time are supported on wasm.
   --> C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\lib.rs:462:1
    |
462 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling lexical-write-float v0.8.5
   Compiling lexical-parse-float v0.8.5
error: could not compile `tokio` due to previous error
warning: build failed, waiting for other jobs to finish...
  [1/4]  Generating your app...success!
  [2/4]  Building your app to Wasm...failed!
⠈ [3/4]  Building server...
```

My cargo.toml:

```
[package]
name = "my-perseus-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus = { version = "0.3.5", features = [ "hydrate" ] }
sycamore = "0.7"
```

The lib.rs code is the same as what's in the link.

This is on Windows 10.

**Comment by arctic-hen7** [comment] 2022-09-15 05:45
What's the output of `perseus --version`?

**Comment by coruscateor** [comment] 2022-09-15 06:25
perseus-cli 0.3.5

**Comment by arctic-hen7** [comment] 2022-09-15 21:38
Does it work with the latest beta (`cargo install perseus-cli --version 0.4.0-beta.9`)? You can run `perseus new test-app` with that to create a testing app automatically.

**Comment by coruscateor** [comment] 2022-09-15 23:38
That worked! So it looks like 3.4 is defunct because of updated dependencies?

**Comment by arctic-hen7** [comment] 2022-09-16 02:53
Interesting. What are the contents of `.perseus/Cargo.toml` in the v0.3.5 one? That might have some clues.

**Comment by coruscateor** [comment] 2022-09-16 21:19
```
# This crate defines the user's app in terms that Wasm can understand, making development significantly simpler.
# IMPORTANT: spacing matters in this file for runtime replacements, do NOT change it!

[package]
name = "perseus-engine"
version = "0.3.5"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# We alias here because the package name will change based on whatever's in the user's manifest
app = { package = "my-perseus-app", path = "../" }

perseus = { version = "0.3.5" }
sycamore = { version = "^0.7.1", features = ["ssr"] }
sycamore-router = "^0.7.1"
web-sys = { version = "0.3", features = ["Event", "Headers", "Request", "RequestInit", "RequestMode", "Response", "ReadableStream", "Window"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1.6"

# This section is needed for Wasm Pack (which we use instead of Trunk for flexibility)
[lib]
crate-type = ["cdylib", "rlib"]

[features]
# This changes a few things to support running as a standalone server binary (this is set by `perseus deploy`, do NOT invoke this manually!)
standalone = []

[workspace]
```

Ok, will do. 

I should point out that the book link under "What's it like?" in the Readme goes to version 3.4.

Cheers

**Comment by arctic-hen7** [comment] 2022-09-16 21:24
Thanks for the reminder about that link, I'll fix that!

That all looks fine, how about `.perseus/builder/Cargo.toml`?

**Comment by coruscateor** [comment] 2022-09-17 03:57
Here ya' go:

```
# This crate defines the build process for Perseus
# This used to be part of the root crate in the engine, but it was moved out of there so feature gating could be different across the server, builder, and client
# IMPORTANT: spacing matters in this file for runtime replacements, do NOT change it!

[package]
name = "perseus-engine-builder"
version = "0.3.5"
edition = "2018"
default-run = "perseus-builder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
perseus-engine = { path = "../" }
perseus = { version = "0.3.5", features = [ "tinker-plugins", "server-side" ] }
futures = "0.3"
fs_extra = "1"
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }
fmterr = "0.1"

# We define a binary for building, serving, and doing both
[[bin]]
name = "perseus-builder"
path = "src/bin/build.rs"

[[bin]]
name = "perseus-exporter"
path = "src/bin/export.rs"

[[bin]]
name = "perseus-tinker" # Yes, the noun is 'tinker', not 'tinkerer'
path = "src/bin/tinker.rs"

[[bin]]
name = "perseus-error-page-exporter"
path = "src/bin/export_error_page.rs"

[workspace]
```

**Comment by arctic-hen7** [comment] 2022-09-17 21:28
Would you try changing `rt-multi-thread` to `rt` in that file? That might work...

**Comment by coruscateor** [comment] 2022-09-18 23:27
the result after running perseus serve:

```
  [1/4]  Generating your app...failed!
  [1/4]  Generating your app...failed!
  [2/4]  Building your app to Wasm...failed!
⢀ [3/4]  Building server...
    Blocking waiting for file lock on package cache
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.4
   Compiling quote v1.0.21
   Compiling syn v1.0.99
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.14.0
   Compiling wasm-bindgen-shared v0.2.83
   Compiling log v0.4.17
   Compiling bumpalo v3.11.0
   Compiling serde_json v1.0.85
   Compiling serde_derive v1.0.144
   Compiling serde v1.0.144
   Compiling itoa v1.0.3
   Compiling ryu v1.0.11
   Compiling wasm-bindgen v0.2.83
   Compiling version_check v0.9.4
   Compiling static_assertions v1.1.0
   Compiling memchr v2.5.0
   Compiling futures-core v0.3.24
   Compiling futures-task v0.3.24
   Compiling futures-channel v0.3.24
   Compiling pin-project-lite v0.2.9
   Compiling fnv v1.0.7
   Compiling futures-sink v0.3.24
   Compiling libc v0.2.132
   Compiling ident_case v1.0.1
   Compiling strsim v0.10.0
   Compiling futures-util v0.3.24
   Compiling hashbrown v0.12.3
   Compiling smallvec v1.9.0
   Compiling minimal-lexical v0.2.1
   Compiling pin-utils v0.1.0
   Compiling utf8-width v0.1.6
   Compiling futures-io v0.3.24
   Compiling thiserror v1.0.35
   Compiling bytes v1.2.1
   Compiling unicode-xid v0.2.3
   Compiling async-trait v0.1.57
   Compiling paste v1.0.9
   Compiling urlencoding v2.1.2
   Compiling fmterr v0.1.1
   Compiling getrandom v0.2.7
   Compiling lexical-util v0.8.5
   Compiling indexmap v1.9.1
   Compiling num-traits v0.2.15
   Compiling slab v0.4.7
   Compiling num-integer v0.1.45
   Compiling tokio v1.21.1
   Compiling html-escape v0.2.11
   Compiling ahash v0.7.6
   Compiling http v0.2.8
   Compiling lexical-write-integer v0.8.5
   Compiling lexical-parse-integer v0.8.6
   Compiling time v0.1.44
   Compiling nom v7.1.1
error: Only features sync,macros,io-util,rt,time are supported on wasm.
   --> C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\lib.rs:462:1
    |
462 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling lexical-write-float v0.8.5
   Compiling lexical-parse-float v0.8.5
   Compiling lexical-core v0.8.5
   Compiling lexical v6.1.1
error: could not compile `tokio` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by arctic-hen7** [comment] 2022-09-19 21:31
Hmm. How about `cargo check` inside `.perseus/engine`?

**Comment by coruscateor** [comment] 2022-09-20 21:44
There is no .perseus/engine directory. However there is a dist\target_engine directory.

**Comment by arctic-hen7** [comment] 2022-09-21 21:37
Oh sorry! I meant `.perseus/builder` in the v0.3.5 one.

**Comment by coruscateor** [comment] 2022-09-21 22:12
```
    Checking cfg-if v1.0.0
    Checking itoa v1.0.3  
    Checking ryu v1.0.11  
    Checking static_assertions v1.1.0
    Checking once_cell v1.14.0
    Checking pin-project-lite v0.2.9
    Checking hashbrown v0.12.3
    Checking futures-sink v0.3.24
    Checking pin-utils v0.1.0
    Checking futures-io v0.3.24
    Checking smallvec v1.9.0
    Checking bytes v1.2.1
    Checking utf8-width v0.1.6
    Checking regex-syntax v0.6.27
    Checking fnv v1.0.7
    Checking fmterr v0.1.1
    Checking urlencoding v2.1.2
    Checking fs_extra v1.2.0
   Compiling tokio v1.21.1
    Checking getrandom v0.2.7
    Checking lexical-util v0.8.5
    Checking html-escape v0.2.11
    Checking memchr v2.5.0
    Checking futures-core v0.3.24
    Checking winapi v0.3.9
    Checking futures-task v0.3.24
    Checking libc v0.2.132
    Checking num-traits v0.2.15
    Checking slab v0.4.7
    Checking ahash v0.7.6
    Checking futures-channel v0.3.24
    Checking http v0.2.8
    Checking indexmap v1.9.1
    Checking serde v1.0.144
    Checking thiserror v1.0.35
    Checking futures-util v0.3.24
    Checking aho-corasick v0.7.19
    Checking lexical-write-integer v0.8.5
    Checking lexical-parse-integer v0.8.6
    Checking num-integer v0.1.45
    Checking lexical-parse-float v0.8.5
    Checking lexical-write-float v0.8.5
    Checking lexical-core v0.8.5
    Checking lexical v6.1.1
    Checking regex v1.6.0
    Checking time v0.1.44
    Checking iana-time-zone v0.1.48
    Checking serde_json v1.0.85
    Checking chrono v0.4.22
    Checking futures-executor v0.3.24
    Checking wasm-bindgen v0.2.83
    Checking futures v0.3.24
    Checking js-sys v0.3.60
    Checking console_error_panic_hook v0.1.7
    Checking web-sys v0.3.60
    Checking wasm-bindgen-futures v0.4.33
    Checking sycamore-reactive v0.7.1
    Checking rexie v0.2.1
    Checking sycamore v0.7.1
    Checking sycamore-router v0.7.1
    Checking perseus v0.3.5
    Checking my-perseus-app v0.1.0 (F:\SoftwareProjects\Rust\my-perseus-app)
    Checking perseus-engine v0.3.5 (F:\SoftwareProjects\Rust\my-perseus-app\.perseus)
    Checking perseus-engine-builder v0.3.5 (F:\SoftwareProjects\Rust\my-perseus-app\.perseus\builder)
error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
 --> src/bin/build.rs:8:1
  |
8 | #[tokio::main]
  | ^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)

error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
 --> src/bin/export_error_page.rs:6:1
  |
6 | #[tokio::main]
  | ^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)

error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
  --> src/bin/export.rs:15:1
   |
15 | #[tokio::main]
   | ^^^^^^^^^^^^^^
   |
   = note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `perseus-engine-builder` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `perseus-engine-builder` due to previous error
error: could not compile `perseus-engine-builder` due to previous error
```

**Comment by arctic-hen7** [comment] 2022-09-22 21:32
Okay, those errors should be caused by what I asked you to change before. This problem seems to be that `tokio` is being built for the browser, which is just plain odd. In v0.4.x, Perseus explicitly target-gates dependencies to make things clearer, but these kinds of issues of dependencies being built for the wrong platform never seemed to happen in the old versions. I wonder if this is a Windows issue somehow. Would you be able to test v0.3.5 on WSL?

**Comment by arctic-hen7** [comment] 2022-09-24 05:35
Oh, great. I'll probably have to release a new version of v0.3.x then, with the Tokio version pinned. I'll pin this issue in the meantime.

**Comment by arctic-hen7** [comment] 2022-09-26 07:47
Alright, this should be fixed in v0.3.6. @coruscateor could you confirm that everything's working with that version, please?

**Comment by coruscateor** [comment] 2022-09-27 23:08
I don't think so:

```
PS F:\SoftwareProjects\Rust\my-perseus-app> cargo install perseus-cli --version 0.3.6
  Downloaded perseus-cli v0.3.6
  Downloaded 1 crate (47.9 KB) in 1.37s
    Updating crates.io index
  Installing perseus-cli v0.3.6
  Downloaded warp v0.3.3
  Downloaded thiserror-impl v1.0.37
  Downloaded thiserror v1.0.37
  Downloaded tokio v1.21.2
  Downloaded serde_derive v1.0.145
  Downloaded webpki-roots v0.22.5
  Downloaded syn v1.0.101
  Downloaded serde v1.0.145
  Downloaded proc-macro2 v1.0.44
  Downloaded 9 crates (1.4 MB) in 4.60s
   Compiling winapi v0.3.9
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.44
   Compiling unicode-ident v1.0.4
   Compiling quote v1.0.21
   Compiling syn v1.0.101
   Compiling autocfg v1.1.0
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling windows_x86_64_msvc v0.36.1
   Compiling once_cell v1.15.0
   Compiling bytes v1.2.1
   Compiling futures-core v0.3.24
   Compiling typenum v1.15.0
   Compiling pin-project-lite v0.2.9
   Compiling itoa v1.0.3
   Compiling fnv v1.0.7
   Compiling futures-task v0.3.24
   Compiling cc v1.0.73
   Compiling futures-channel v0.3.24
   Compiling futures-sink v0.3.24
   Compiling tinyvec_macros v0.1.0
   Compiling futures-util v0.3.24
   Compiling serde v1.0.145
   Compiling num_cpus v1.13.1
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.24
   Compiling httparse v1.8.0
   Compiling percent-encoding v2.2.0
   Compiling libc v0.2.133
   Compiling spin v0.5.2
   Compiling cpufeatures v0.2.5
   Compiling base64 v0.13.0
   Compiling untrusted v0.7.1
   Compiling unicode-bidi v0.3.8
   Compiling ppv-lite86 v0.2.16
   Compiling hashbrown v0.12.3
   Compiling thiserror v1.0.37
   Compiling proc-macro-hack v0.5.19
   Compiling crossbeam-utils v0.8.11
   Compiling crc32fast v1.3.2
   Compiling bitflags v1.3.2
   Compiling mime v0.3.16
   Compiling anyhow v1.0.65
   Compiling ryu v1.0.11
   Compiling fastrand v1.8.0
   Compiling utf-8 v0.7.6
   Compiling httpdate v1.0.2
   Compiling safemem v0.3.3
   Compiling rustls v0.20.6
   Compiling try-lock v0.2.3
   Compiling regex-syntax v0.6.27
   Compiling adler v1.0.2
   Compiling serde_json v1.0.85
   Compiling encode_unicode v0.3.6
   Compiling byteorder v1.4.3
   Compiling serde_derive v1.0.145
   Compiling lazy_static v1.4.0
   Compiling os_str_bytes v6.3.0
   Compiling tower-service v0.3.2
   Compiling heck v0.4.0
   Compiling quick-error v1.2.3
   Compiling chunked_transfer v1.4.0
   Compiling scoped-tls v1.0.0
   Compiling unicode-width v0.1.10
   Compiling strsim v0.10.0
   Compiling textwrap v0.15.1
   Compiling glob v0.3.0
   Compiling number_prefix v0.4.0
   Compiling fmterr v0.1.1
   Compiling fs_extra v1.2.0
   Compiling getrandom v0.2.7
   Compiling tracing-core v0.1.29
   Compiling generic-array v0.14.6
   Compiling unicase v2.6.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling slab v0.4.7
   Compiling tokio v1.21.2
   Compiling indexmap v1.9.1
   Compiling http v0.2.8
   Compiling tinyvec v1.6.0
   Compiling form_urlencoded v1.1.0
   Compiling rustls-pemfile v0.2.1
   Compiling miniz_oxide v0.5.4
   Compiling clap_lex v0.2.4
   Compiling rand_core v0.6.4
   Compiling ring v0.16.20
   Compiling regex v1.6.0
   Compiling rand_chacha v0.3.1
   Compiling http-body v0.4.5
   Compiling headers-core v0.2.0
   Compiling tracing v0.1.36
   Compiling want v0.3.0
   Compiling unicode-normalization v0.1.22
   Compiling windows-sys v0.36.1
   Compiling buf_redux v0.8.4
   Compiling twoway v0.1.8
   Compiling crossbeam-channel v0.5.6
   Compiling flate2 v1.0.24
   Compiling rand v0.8.5
   Compiling mime_guess v2.0.4
   Compiling idna v0.3.0
   Compiling block-buffer v0.10.3
   Compiling crypto-common v0.1.6
   Compiling toml v0.5.9
   Compiling serde_urlencoded v0.7.1
   Compiling url v2.3.1
   Compiling digest v0.10.5
   Compiling mio v0.8.4
   Compiling filetime v0.2.17
   Compiling sha-1 v0.10.0
   Compiling sha1 v0.10.5
   Compiling socket2 v0.4.7
   Compiling winapi-util v0.1.5
   Compiling remove_dir_all v0.5.3
   Compiling terminal_size v0.1.17
   Compiling atty v0.2.14
   Compiling command-group v1.0.8
   Compiling ctrlc v3.2.3
   Compiling headers v0.3.8
   Compiling same-file v1.0.6
   Compiling termcolor v1.1.3
   Compiling tempfile v3.3.0
   Compiling console v0.15.1
   Compiling console v0.14.1
   Compiling walkdir v2.3.2
   Compiling webpki v0.22.0
   Compiling sct v0.7.0
   Compiling multipart v0.18.0
   Compiling indicatif v0.17.0-beta.1
   Compiling notify v5.0.0-pre.13
   Compiling futures-macro v0.3.24
   Compiling tokio-macros v1.8.0
   Compiling thiserror-impl v1.0.37
   Compiling pin-project-internal v1.0.12
   Compiling clap_derive v3.2.18
   Compiling include_dir_impl v0.6.2
   Compiling ureq v2.5.0
   Compiling include_dir v0.6.2
   Compiling pin-project v1.0.12
   Compiling tungstenite v0.17.3
   Compiling clap v3.2.22
   Compiling cargo_toml v0.9.2
   Compiling tokio-util v0.7.4
   Compiling tokio-stream v0.1.10
   Compiling h2 v0.3.14
   Compiling tokio-tungstenite v0.17.2
   Compiling futures-executor v0.3.24
   Compiling futures v0.3.24
   Compiling hyper v0.14.20
   Compiling warp v0.3.3
   Compiling perseus-cli v0.3.6
    Finished release [optimized] target(s) in 3m 00s
   Replacing C:\Users\Paul\.cargo\bin\perseus.exe
    Replaced package `perseus-cli v0.4.0-beta.10` with `perseus-cli v0.3.6` (executable `perseus.exe`)
PS F:\SoftwareProjects\Rust\my-perseus-app> perseus serve
⢀ [1/4]  Generating your app...
  [2/4]  Building your app to Wasm...failed!
⠄ [3/4]  Building server...
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Blocking waiting for file lock on package cache
   Compiling tokio v1.21.1
   Compiling lexical-core v0.8.5
   Compiling num-integer v0.1.45
   Compiling serde_derive v1.0.144
   Compiling wasm-bindgen-backend v0.2.83
   Compiling darling_core v0.13.4
   Compiling futures-macro v0.3.24
   Compiling sycamore-macro v0.7.1
   Compiling thiserror-impl v1.0.35
   Compiling sycamore-router-macro v0.7.1
   Compiling async-trait v0.1.57
error: Only features sync,macros,io-util,rt,time are supported on wasm.
   --> C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\lib.rs:462:1
    |
462 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling lexical v6.1.1
   Compiling wasm-bindgen-macro-support v0.2.83
   Compiling futures-util v0.3.24
error: could not compile `tokio` due to previous error
warning: build failed, waiting for other jobs to finish...
  [1/4]  Generating your app...failed!
  [2/4]  Building your app to Wasm...failed!
⠐ [3/4]  Building server...
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
   Compiling tokio v1.21.1
   Compiling rexie v0.2.1
   Compiling perseus v0.3.5
   Compiling my-perseus-app v0.1.0 (F:\SoftwareProjects\Rust\my-perseus-app)
   Compiling perseus-engine v0.3.5 (F:\SoftwareProjects\Rust\my-perseus-app\.perseus)
   Compiling perseus-engine-builder v0.3.5 (F:\SoftwareProjects\Rust\my-perseus-app\.perseus\builder)
error: The default runtime flavor is `multi_thread`, but the `rt-multi-thread` feature is disabled.
 --> src/bin/build.rs:8:1
  |
8 | #[tokio::main]
  | ^^^^^^^^^^^^^^
  |
  = note: this error originates in the attribute macro `tokio::main` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `perseus-engine-builder` due to previous error
```

**Comment by arctic-hen7** [comment] 2022-09-28 21:46
Make sure you've run `perseus clean && cargo update` first?

**Comment by coruscateor** [comment] 2022-09-30 00:41
```
PS F:\SoftwareProjects\Rust\my-perseus-app> perseus clean
PS F:\SoftwareProjects\Rust\my-perseus-app> cargo update
    Updating crates.io index
    Updating iana-time-zone v0.1.48 -> v0.1.50
    Updating libc v0.2.132 -> v0.2.134
    Updating once_cell v1.14.0 -> v1.15.0
    Updating perseus v0.3.5 -> v0.3.6
    Updating perseus-macro v0.3.5 -> v0.3.6
    Updating proc-macro2 v1.0.43 -> v1.0.46
    Updating serde v1.0.144 -> v1.0.145
    Updating serde_derive v1.0.144 -> v1.0.145
    Updating syn v1.0.99 -> v1.0.101
    Updating thiserror v1.0.35 -> v1.0.37
    Updating thiserror-impl v1.0.35 -> v1.0.37
    Updating tokio v1.21.1 -> v1.20.1
    Updating unicode-xid v0.2.3 -> v0.2.4
PS F:\SoftwareProjects\Rust\my-perseus-app> cargo install perseus-cli --version 0.3.6
     Ignored package `perseus-cli v0.3.6` is already installed, use --force to override
PS F:\SoftwareProjects\Rust\my-perseus-app> perseus serve
  [1/4]  Generating your app...success!
  [2/4]  Building your app to Wasm...success!
  [3/4]  Building server...success!
  [4/4]  Your app is now live on <http://127.0.0.1:8080>! To change this, re-run this command with different settings for `--host` and `--port`.
```

That worked! 

So should I use 0.3.6 over 0.4.0-beta.9?

**Comment by arctic-hen7** [comment] 2022-09-30 21:29
Fantastic! Use whichever you prefer, honestly. 0.4.x should be faster and a bit better overall, but the docs are more complete for v0.3.6.

**Closed** 2022-09-30 21:29 UTC
